import type { Locale } from "@/lib/i18n";
import type { FulfillType } from "@/lib/upcoming/fence";

/** SQUARE NEXT copy. Spanish first, as the cocina board is. */
export const NEXT_COPY = {
  es: {
    title: "Tacos4Groups · Próximos",
    month: "Mes",
    week: "Semana",
    list: "Lista",
    today: "Hoy",
    prev: "Anterior",
    next: "Siguiente",
    refresh: "Actualizar",
    updated: "Actualizado",
    never: "Nunca",
    stale: "No se pudo leer C1. Estos pedidos pueden estar viejos.",
    heldBack: (n: number) =>
      `${n} ${n === 1 ? "pedido retenido" : "pedidos retenidos"} por la revisión de privacidad. Ver el ticket de C1.`,
    testData: "Datos de prueba",
    empty: "No hay pedidos próximos.",
    off: "Próximos está apagado en esta computadora.",
    columns: "Mostrar",
    guests: "Personas",
    fulfill: "Entrega/Recoger",
    ready: "Listo a las",
    modifiers: "Detalles",
    eventTime: "Hora del evento",
    stripReady: "Listo",
    peopleCount: (n: number) => `${n} ${n === 1 ? "persona" : "personas"}`,
    date: "Fecha",
    lines: "Líneas de cocina",
    close: "Cerrar",
    backToList: "Volver a la lista",
    options: "Opciones",
    noOrdersDay: "Sin pedidos",
    t4gEmptyToday: "Sin órdenes T4G hoy",
    t4gEmptyDay: "Sin órdenes T4G este día",
    checksEvery: "Se revisa cada 5 minutos.",
    lineCount: (n: number) => `${n} ${n === 1 ? "línea" : "líneas"}`,
    orderCount: (n: number) => `${n} ${n === 1 ? "pedido" : "pedidos"}`,
    confirm: "confirmar",
    back: "Tablero",
    weekdays: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    fulfillType: { PICKUP: "RECOGER", DELIVERY: "ENTREGA" } as Record<FulfillType, string>,
    print: "Imprimir",
    reprint: "Reimprimir (CAMBIO)",
    printing: "Imprimiendo…",
    printOk: "Enviado a la impresora morada. Revisa que salieron 4 tickets.",
    printBlocked: (why: string) => `No imprimió: ${why}. Arréglala y toca Imprimir otra vez.`,
    printUncertain: "Revisa la impresora, no vuelvas a tocar.",
    printBusy: "Ya se está imprimiendo.",
    printRefused: "No se pudo preparar el ticket. Avisa al gerente.",
    printManagerOnly: "Solo un gerente puede imprimir.",
    printWhy: {
      paper_out: "sin papel",
      paper_end_stop: "sin papel",
      cover_open: "tapa abierta",
      offline: "apagada",
      no_response: "no responde",
      wrong_model: "no es la impresora correcta",
      feed_button: "botón de papel presionado",
      autocutter_error: "error del cortador",
      error_occurred: "error de la impresora",
      unrecoverable_error: "error de la impresora",
      auto_recoverable_error: "error de la impresora",
    } as Record<string, string>,
  },
  en: {
    title: "Tacos4Groups · Next",
    month: "Month",
    week: "Week",
    list: "List",
    today: "Today",
    prev: "Previous",
    next: "Next",
    refresh: "Refresh",
    updated: "Updated",
    never: "Never",
    stale: "Could not read C1. These orders may be old.",
    heldBack: (n: number) =>
      `${n} ${n === 1 ? "order" : "orders"} held back by the privacy check. See the C1 ticket.`,
    testData: "Test data",
    empty: "No upcoming orders.",
    off: "Next is off on this computer.",
    columns: "Show",
    guests: "Guests",
    fulfill: "Pickup/Delivery",
    ready: "Ready by",
    modifiers: "Details",
    eventTime: "Event time",
    stripReady: "Ready",
    peopleCount: (n: number) => `${n} ${n === 1 ? "person" : "people"}`,
    date: "Date",
    lines: "Kitchen lines",
    close: "Close",
    backToList: "Back to the list",
    options: "Options",
    noOrdersDay: "No orders",
    t4gEmptyToday: "No T4G orders today",
    t4gEmptyDay: "No T4G orders this day",
    checksEvery: "Checked every 5 minutes.",
    lineCount: (n: number) => `${n} ${n === 1 ? "line" : "lines"}`,
    orderCount: (n: number) => `${n} ${n === 1 ? "order" : "orders"}`,
    confirm: "confirm",
    back: "Board",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    fulfillType: { PICKUP: "PICKUP", DELIVERY: "DELIVERY" } as Record<FulfillType, string>,
    print: "Print",
    reprint: "Reprint (CAMBIO)",
    printing: "Printing…",
    printOk: "Sent to the purple printer. Check that 4 tickets came out.",
    printBlocked: (why: string) => `Did not print: ${why}. Fix it and tap Print again.`,
    printUncertain: "Check the printer, do not tap again.",
    printBusy: "Already printing.",
    printRefused: "The ticket could not be prepared. Tell the manager.",
    printManagerOnly: "Only a manager can print.",
    printWhy: {
      paper_out: "out of paper",
      paper_end_stop: "out of paper",
      cover_open: "cover open",
      offline: "off",
      no_response: "not answering",
      wrong_model: "not the expected printer",
      feed_button: "paper button held",
      autocutter_error: "cutter error",
      error_occurred: "printer error",
      unrecoverable_error: "printer error",
      auto_recoverable_error: "printer error",
    } as Record<string, string>,
  },
} satisfies Record<Locale, unknown>;

export type NextCopy = (typeof NEXT_COPY)["es"];

/** NEXT card and detail: guests are C1's estimate, so those surfaces print the label. */
export function guestsText(guests: number, t: NextCopy): string {
  return `${guests} (${t.confirm})`;
}
